modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/plonco/solo_leveling_system/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://github.com/plonco/solo_leveling_system/update.json"
displayURL="https://github.com/plonco/solo_leveling_system"
description='''
A mod for solo leveling system in Minecraft.
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="java"
mandatory=true
versionRange="[17,)"
ordering="NONE"
side="BOTH"