modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="solo_leveling_system"
version="1.0.0"
displayName="Solo Leveling System"
authors="plonco"
description='''
A mod that adds a Solo Leveling System to Minecraft
'''

[[dependencies.solo_leveling_system]]
modId="forge"
mandatory=true
versionRange="[47.3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.solo_leveling_system]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="AFTER"
side="BOTH"

[modproperties.solo_leveling_system]
catalogueImageIcon="icon.png"
displayTest="MATCH_VERSION"
environment="both"